#:schema https://mise.jdx.dev/schema/mise.json
#:tombi toml-version = "v1.1.0"
#:tombi schema.strict = true
############
# Settings #
############
[settings]
lockfile = true
experimental = true
minimum_release_age = "7d"

[settings.npm]
package_manager = "pnpm"

[settings.pipx]
uvx = true

[settings.github]
credential_command = "gh auth token"

#########
# Tools #
#########
[tools]

# Language Runtimes
go = "1.26.4"
lua = "5.4.8"
perl = "5.42.2"
php = "8.5.7"
python = {
  version = "3.14.6",
  postinstall = "$MISE_TOOL_INSTALL_PATH/bin/python -m pip install pyyaml",
}
ruby = "4.0.5"
node = "26.3.0"
rust = "1.96.0"

# Package Managers
pnpm = "latest"
uv = "latest"
"github:composer/composer" = { version = "latest", asset_pattern = "composer.phar", bin = "composer" }
"github:php/pie" = { version = "latest", asset_pattern = "pie.phar", bin = "pie" }

# CLI Tools
"npm:aws-cdk" = "latest"
"npm:ccusage" = "latest"
"npm:difit" = "latest"
"npm:npm-check-updates" = "latest"
"npm:@playwright/cli" = "latest"
"github:cross-ts/rss-reader" = "v0.4.12"

# Language Servers
"gem:ruby-lsp" = "latest"
"github:LuaLS/lua-language-server" = "3.18.2"
"go:github.com/docker/docker-language-server/cmd/docker-language-server" = "latest"
"npm:bash-language-server" = "latest"
"npm:intelephense" = "latest"
"github:AJenbo/phpantom_lsp" = "latest"
"npm:tombi" = "latest"
"npm:typescript-language-server" = "latest"
"npm:vscode-langservers-extracted" = "latest"
"npm:yaml-language-server" = "latest"
"npm:@actions/languageserver" = "latest"
"npm:@ansible/ansible-language-server" = "latest"
"npm:@github/copilot-language-server" = "latest"
"pipx:nginx-language-server" = "latest"
"pipx:python-lsp-server" = "latest"
"http:terraform-ls" = {
  version = "0.38.3",
  url = "https://releases.hashicorp.com/terraform-ls/{{version}}/terraform-ls_{{version}}_{{ exec(command='uname -s') | lower }}_{{ exec(command='uname -m') }}.zip",
  version_list_url = "https://api.github.com/repos/hashicorp/terraform-ls/releases",
}

# Linter
"github:checkmake/checkmake" = "latest"
"github:hadolint/hadolint" = "latest"
"github:phpstan/phpstan" = { version = "latest", asset_pattern = "phpstan.phar", bin = "phpstan" }
"github:squizlabs/PHP_CodeSniffer" = { version = "latest", asset_pattern = "phpcs.phar", bin = "phpcs" }
"go:github.com/rhysd/actionlint/cmd/actionlint" = "latest"
"npm:markdownlint-cli2" = "latest"
"npm:@quobix/vacuum" = "latest"
"pipx:ansible-lint" = "latest"
"pipx:mypy" = "latest"
"pipx:yamllint" = "latest"

# Formatter
"cargo:shellharden" = "latest"
"cargo:stylua" = "latest"
"pipx:isort" = "latest"
