######
# AI #
######
[[snippets]]
tag = ["codex"]
command = "codex --no-daemon --profile $(print -l ${CODEX_HOME}/*.config.toml(:t:r:r) | fzf --ansi --height 40%)"

###################
# Version Manager #
###################
[[snippets]]
tag = ["homebrew", "update"]
command = "brew bundle"

[[snippets]]
tag = ["mise", "update"]
command = "mise up --bump"

[[snippets]]
tag = ["sheldon", "update"]
command = "sheldon lock --update"

[[snippets]]
tag = ["neovim", "update"]
command = "nvim --headless '+Lazy! sync' +qa"

########
# tmux #
########
[[snippets]]
tag = ["tmux"]
command = "tmux attach-session -t $(tmux list-sessions -F '#{session_name}' | fzf)"

[[snippets]]
tag = ["tmux"]
command = "tmux new-session -s <session-name>"

#############
# Benchmark #
#############
[[snippets]]
tag = ["benchmark", "zsh"]
command = "hyperfine --warmup 10 --shell=none 'zsh -i -c exit' 'zsh -i --no-global-rcs -c exit' 'zsh -i --no-rcs -c exit'"

[[snippets]]
tag = ["benchmark", "neovim"]
command = "hyperfine --warmup 10 --shell=none 'nvim --headless -c qall!' 'nvim --headless -u NONE -c qall!'"
