#!/usr/bin/env ruby
# frozen_string_literal: true

#######
# Tap #
#######
tap 'hashicorp/tap'
tap 'hanasuke/moralerspace'

########
# Font #
########
cask 'font-Hack-nerd-font'
cask 'font-moralerspace'

############
# AI Tools #
############
# CLI
cask 'antigravity-cli'
cask 'claude-code'
cask 'codex'
cask 'copilot-cli'

# AI Apps
cask 'antigravity'
cask 'google-gemini'
cask 'chatgpt'
cask 'claude'

# AI Terminal Emulator
cask 'cmux'
cask 'stablyai/orca/orca'

############
# Terminal #
############
# Emulator
cask 'ghostty'

# Multiplexer
brew 'tmux'

# Shell
brew 'bash'
brew 'fish'
brew 'zsh'

# Shell Prompt
brew 'starship'

# Dependency Manager
brew 'mise'
brew 'sheldon'

# Editor
cask 'obsidian'
brew 'neovim'
brew 'neovim-remote'
brew 'tree-sitter-cli'
brew 'universal-ctags'

# Git
brew 'git'
brew 'git-extras'
brew 'ghq'
brew 'tig'

# GitHub
brew 'gh'
brew 'pinact'

# Database
brew 'sqlite'
brew 'duckdb'

# Utilities
brew 'ripgrep'
brew 'bat'
brew 'eza'
brew 'fd'
brew 'fzf'
brew 'hyperfine'
brew 'jq'
brew 'pet'
brew 'marp-cli'
brew 'tree'
brew 'yq'
if OS.mac?
  brew 'coreutils'
  brew 'make'
  brew 'watch'
  brew 'yap'
end

# Build PHP
if OS.mac?
  brew 'autoconf'
  brew 'automake'
  brew 'bison'
  brew 'freetype'
  brew 'gd'
  brew 'gettext'
  brew 'icu4c'
  brew 'krb5'
  brew 'libedit'
  brew 'libiconv'
  brew 'libjpeg'
  brew 'libpng'
  brew 'libxml2'
  brew 'libzip'
  brew 'pkg-config'
  brew 're2c'
  brew 'readline'
  brew 'zlib'
  brew 'gmp'
  brew 'libsodium'
  brew 'imagemagick'
end

##################
# Infrastructure #
##################
brew 'awscli'
brew 'aws-sam-cli'
brew 'ansible'
brew 'hashicorp/tap/terraform'
brew 'alp'

############
# Browsers #
############
cask 'google-chrome'

#######################
# Communication Tools #
#######################
cask 'discord'
cask 'slack'
cask 'zoom'

##############
# Other Apps #
##############
cask '1password'
cask '1password-cli'
cask 'docker-desktop'
cask 'steam'
