#:schema https://raw.githubusercontent.com/openai/codex/refs/heads/main/codex-rs/core/config.schema.json
#:tombi toml-version = "v1.1.0"
#:tombi schema.strict = true
personality = "pragmatic"
model = "gpt-6-astra"
model_reasoning_effort = "low"
