name: Lazy Update

on:
  workflow_dispatch:
  push:
    branches:
      - main

jobs:
  lazy-update:
    runs-on: ubuntu-latest
    timeout-minutes: 3
    steps:
      - uses: actions/checkout@v4
      - uses: rhysd/action-setup-vim@v1
        with:
          version: stable
          neovim: true
      - run: nvim --headless "+Lazy! sync" +qa
        env:
          XDG_CONFIG_HOME: ${{ github.workspace }}
          XDG_DATA_HOME: /tmp
