name: Lazy Update

on:
  workflow_dispatch:
  push:
    branches:
      - main

jobs:
  lazy-update:
    runs-on: ubuntu-latest
    steps:
      - run: apt-get install neovim
      - run: nvim --headless "+Lazy! sync" +qa
